language: generic
dist: xenial
jdk: openjdk8

env:
  global:
    BYOND_MAJOR="512"
    BYOND_MINOR="1485"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
matrix:
    include:
    - name: "Code"
      env: TEST=CODE
    - name: "Map - Torch"
      env: TEST=MAP MAP_PATH=torch
    - name: "Map - Example"
      env: TEST=MAP MAP_PATH=example
    - name: "Map - Bearcat"
      env: TEST=MAP MAP_PATH=bearcat
    - name: "Map - Away Sites"
      env: TEST=MAP MAP_PATH=away_sites_testing

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

      install:
        - tools/travis/install_build_tools.sh
        - tools/travis/install_spaceman_dmm.sh dreamchecker
        - python3 -m pip install -r tools/mapmerge2/requirements.txt
      script:
        - tools/travis/check_filedirs.sh baystation12.dme
        - tools/travis/check_changelogs.sh
        - find . -name "*.php" -print0 | xargs -0 -n1 php -l
        - find . -name "*.json" -not -path "*/node_modules/*" -print0 | xargs -0 python3 ./tools/json_verifier.py
        - tools/travis/build_tgui.sh
        - tools/travis/check_grep.sh
        - python3 tools/mapmerge2/dmi.py --test
        - ~/dreamchecker
        
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip
      - uchardet

script:
  - test/run-test.sh

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
