name: CI Suite
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: true
      matrix:
        test: ["CODE", "MAP"]
        map: ["torch", "bearcat", "example", "away_sites_testing"]
        exclude:
          - test: "CODE"
            map: "bearcat"
          - test: "CODE"
            map: "bearcat"
          - test: "CODE"
            map: "away_sites_testing"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Workspace
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install libc6-i386 libgcc1:i386 libstdc++6:i386 python python-pip uchardet dos2unix
      - name: Run Checks
        env:
          TEST: ${{ matrix.test }}
          MAP: ${{ matrix.map }}
        run: |
          sudo chmod +x test/run-test.sh
          bash test/run-test.sh
          
